Fix problems found on fresh install
 * Sealing failures on update-initramfs are no longer fatal, but instead
   loudly warn. Still, there should be some mechanism to short-circuit
   the attempt to seal on the initial install since we know a priori
   that we are in the wrong boot chain.

 * Detect the edge case in which there is no matching LUKS key rather
   than fail silently.

 * Add the new LUKS key first, *then* update.

diff --git a/kernel-hooks/update-emboot b/kernel-hooks/update-emboot
--- a/kernel-hooks/update-emboot
+++ b/kernel-hooks/update-emboot
@@ -27,7 +27,13 @@ case $cmd:$mode:$DPKG_MAINTSCRIPT_PACKAGE in
 	;;
     */post-update.d/*:*:|*/post-update.d/*:*:*)
         krel=$arg1
-        exec update-emboot ${krel:+-k "$krel"}
+        set +e
+        update-emboot ${krel:+-k "$krel"}
+        rc=$?
+        if [ "$rc" -ne 0 ]; then
+            echo "update-emboot failed with exit code $rc" >&2
+            echo "WARNING: system may be unbootable!" >&2
+        fi
         ;;
 esac
 
