Improve UX
- Add ability to pause after unseal for easier observation during boot process.

- Add verbose output variable to config. First use is to dump the relevant PCRs
  to the console during the boot process.

- Add help message to update-emboot.

- Provide better argument processing and sanity checking to update-emboot.

- Add option to update-emboot for sealing-only operation.

- Do not allow token removal and sealing in the same run of update-emboot,
  allowing sealing to target a specific kernel release with -k.

diff --git a/kernel-hooks/update-emboot b/kernel-hooks/update-emboot
--- a/kernel-hooks/update-emboot
+++ b/kernel-hooks/update-emboot
@@ -15,7 +15,7 @@ if type systemd-detect-virt >/dev/null 2>&1 &&
 	exit 0
 fi
 
-set -- $DEB_MAINT_PARAMS
+eval set -- $DEB_MAINT_PARAMS
 mode="${1#\'}"
 mode="${mode%\'}"
 case $cmd:$mode:$DPKG_MAINTSCRIPT_PACKAGE in
@@ -24,7 +24,23 @@ case $cmd:$mode:$DPKG_MAINTSCRIPT_PACKAGE in
 	;;
     */postrm.d/*::*|*/postrm.d/*:remove:*)
         krel=$arg1
-        exec update-emboot -i ${krel:+-r -k "$krel"}
+        if [ -n "$krel" ]; then
+            set +e
+            update-emboot ${krel:+-r -k "$krel"}
+            rc=$?
+            if [ "$rc" -ne 0 ]; then
+                echo "update-emboot failed with exit code $rc" >&2
+                echo "WARNING: token removal failed for $krel" >&2
+            fi
+            update-emboot -i
+            rc=$?
+            if [ "$rc" -ne 0 ]; then
+                echo "update-emboot failed with exit code $rc" >&2
+                echo "WARNING: monotonic counter may have failed to increment" >&2
+            fi
+        else
+            echo "WARNING: kernel release not specified for removal operation" >&2
+        fi
 	;;
     */post-update.d/*:*:|*/post-update.d/*:*:*)
         krel=$arg1
diff --git a/update-emboot b/update-emboot
--- a/update-emboot
+++ b/update-emboot
@@ -6,19 +6,34 @@ inc_counter=
 krel=
 remove=
 no_seal=
-while getopts 'ik:rS' opt; do
+while getopts 'ik:rsSh' opt; do
     case "$opt" in
         i) inc_counter=1 ;;
         k) krel=$OPTARG ;;
         r) remove=1 ;;
+        s) seal_only=1 ;;
         S) no_seal=1 ;;
+        h)
+            cat >&2 <<EOF
+syntax: $(basename $0) <options>
+
+operations: (default is to update loader(s) and seal)
+  -r                   Remove token for given kernel release (requires -k)
+  -s                   Do not update loader(s): seal/create token(s) only
+  -S                   Do not seal/create token(s): update loader(s) only
+  -h                   Help
+
+parameters:
+  -i                   Increment monotonic counter before sealing
+  -k <kernel release>  Apply operation to given kernel release only
+EOF
+            exit 0
+            ;;
         :) echo "$OPTARG requires an argument" >&2; exit 1;;
         ?) echo "unknown argument" >&2; exit 1;;
     esac
 done
 shift $((OPTIND-1))
-
-[ -z "$remove" -o -n "$krel" ] || { echo "-r requires -k to be specified"; exit 1; }
 
 [ -r /etc/efi-measured-boot/config ] && . /etc/efi-measured-boot/config
 if [[ $cmd = ./* ]]; then APPDIR=.; fi
@@ -28,18 +43,29 @@ if [[ $cmd = ./* ]]; then APPDIR=.; fi
 set -e
 
 if [ -n "$remove" ]; then
+    [ -n "$krel" ] || { echo "-r requires -k to be specified"; exit 1; }
+
     rootdev=( $(get_device_info /) )
     cryptdev=( $(get_crypttab_entry "${rootdev[1]}") )
     remove_luks_token "${cryptdev[1]}" "$krel"
+    exit 0
+else
+    [ -z "$seal_only" -o -z "$no_seal" ] || { echo "conflicting operations -s and -S"; exit 1; }
+    [ -z "$no_seal" -o -z "$inc_counter" ] || { echo "cannot increment counter without sealing"; exit 1; }
+    [ -z "$inc_counter" -o -z "$krel" ] || { echo "cannot increment counter and specify kernel release"; exit 1; }
+
+    if [ -z "$seal_only" ]; then
+        "$APPDIR"/emboot_install ${krel:+-k "$krel"}
+        "$APPDIR"/emboot_update_efi_apps
+        "$APPDIR"/emboot_update_efi_boot_order
+    fi
+
+    if [ -z "$no_seal" ]; then
+        if [ -n "$inc_counter" ]; then
+            echo "Incrementing monotonic counter" 1>&2
+            increment_counter
+        fi
+
+        "$APPDIR"/emboot_seal_key ${krel:+-k "$krel"}
+    fi
 fi
-
-"$APPDIR"/emboot_install ${krel:+-k "$krel"}
-"$APPDIR"/emboot_update_efi_apps
-"$APPDIR"/emboot_update_efi_boot_order
-
-if [ -n "$inc_counter" ]; then
-    echo "Incrementing monotonic counter" 1>&2
-    increment_counter
-fi
-
-[ -n "$no_seal" ] || "$APPDIR"/emboot_seal_key
