WIP

diff --git a/emboot_unseal b/emboot_unseal
--- a/emboot_unseal
+++ b/emboot_unseal
@@ -2,10 +2,12 @@
 
 exec 3>&1 1>&2
 
+cmd=$0
+
 keyscript="/lib/cryptsetup/askpass"
 keyscriptarg="Please unlock disk $CRYPTTAB_NAME: "
 
-trap 'rc=$?; [ "$rc" -eq 0 ] && exit 0; umount_efi; echo "$(basename $0) failed with exit code $rc"; -n "$oldpwd" && cd "$oldpwd"; exec "$keyscript" "$keyscriptarg" 1>&3 3>&-' EXIT
+trap 'rc=$?; [ "$rc" -eq 0 ] && exit 0; umount_efi; echo "$(basename $cmd) failed with exit code $rc"; -n "$oldpwd" && cd "$oldpwd"; exec "$keyscript" "$keyscriptarg" 1>&3 3>&-' EXIT
 
 set -e
 
@@ -15,8 +17,8 @@ if [ "$CRYPTTAB_TRIED" = 0 ]; then
     oldpwd=$(pwd)
     cd "$emboot_tmp"
 
-    . /etc/efi-measured-boot/functions
     . /etc/efi-measured-boot/config
+    . "$APPDIR"/functions
 
     mount_efi
     for i in counter sealed.pub sealed.priv; do
@@ -26,11 +28,11 @@ if [ "$CRYPTTAB_TRIED" = 0 ]; then
 
     create_provision_context
     if unseal_data 1>&3 3>&-; then
-        echo "$(basename $0) succeeded"
+        echo "$(basename $cmd) succeeded"
         exit 0
     fi
 
-    echo "$(basename $0) failed"
+    echo "$(basename $cmd) failed"
     cd "$oldpwd"
 fi
 
