Token management
 * Remove tokens when the associated kernel is removed.

 * For consistency, change references to "seal_metadata" to "token".

 * Add -k and -r options to emboot_install and emboot_seal_key to allow
   for removal of specific loaders and tokens, respectively.

 * On postinst/postrm, update only the specific kernel changed. This
   change is probably wrong, because changing the set of installed
   kernels might properly change both loaders.

diff --git a/emboot_seal_key b/emboot_seal_key
--- a/emboot_seal_key
+++ b/emboot_seal_key
@@ -5,11 +5,13 @@ cmd=$0
 exec 3>&1 >&2
 
 krel=
-while getopts 'k:' opt; do
+remove=
+while getopts 'k:r' opt; do
     case "$opt" in
         k) krel=$OPTARG ;;
-        :) echo "$OPTARG requires an argument" >&2; return 1;;
-        ?) echo "unknown argument" >&2; return 1;;
+        r) remove=1 ;;
+        :) echo "$OPTARG requires an argument"; exit 1;;
+        ?) echo "unknown argument"; exit 1;;
     esac
 done
 shift $((OPTIND-1))
@@ -21,13 +23,15 @@ if [[ $cmd = ./* ]]; then APPDIR=.; fi
 
 set -e
 
+[ -z "$remove" -o -n "$krel" ] || { echo "-r requires -k to be specified"; exit 1; }
+
 . "$(emboot_state_file)"
 
 cleanup() {
     rc=$?
     [ -n "$tmpdir" ] && rm -rf "$tmpdir"
     [ "$rc" -eq 0 ] && exit 0
-    echo "$(basename "$cmd") failed with exit code $rc" >&2
+    echo "$(basename "$cmd") failed with exit code $rc"
     exit $rc
 }
 
@@ -42,13 +46,18 @@ read_efi_vars
 rootdev=( $(get_device_info /) )
 cryptdev=( $(get_crypttab_entry "${rootdev[1]}") )
 
-if [ -z "$krel" -o "$krel" = "$primary" ]; then
-    echo "Sealing key to primary EFI loader ($primary)"
-    seal_to_loader "$tmpdir" "${cryptdev[1]}" "$(emboot_loader_unix_path)" "$primary"
-fi
-if [ -z "$krel" -o "$krel" = "$old" ]; then
-    echo "Sealing key to old EFI loader ($old)"
-    seal_to_loader "$tmpdir" "${cryptdev[1]}" "$(emboot_loader_unix_path emboot_old.efi)" "$old"
+if [ -n "$remove" ]; then
+    echo "Removing tokens for $krel (if any)"
+    remove_luks_token "${cryptdev[1]}" "$krel"
+else
+    if [ -z "$krel" -o "$krel" = "$primary" ]; then
+        echo "Sealing key to primary EFI loader ($primary)"
+        seal_to_loader "$tmpdir" "${cryptdev[1]}" "$(emboot_loader_unix_path)" "$primary"
+    fi
+    if [ -z "$krel" -o "$krel" = "$old" ]; then
+        echo "Sealing key to old EFI loader ($old)"
+        seal_to_loader "$tmpdir" "${cryptdev[1]}" "$(emboot_loader_unix_path emboot_old.efi)" "$old"
+    fi
 fi
 
 exit 0
