Honing style

diff --git a/emboot_update_efi_boot_order b/emboot_update_efi_boot_order
--- a/emboot_update_efi_boot_order
+++ b/emboot_update_efi_boot_order
@@ -2,7 +2,7 @@
 
 cmd=$0
 
-exec 3>&1 1>&2
+exec 3>&1 >&2
 
 [ -r /etc/efi-measured-boot/config ] && . /etc/efi-measured-boot/config
 if [[ $cmd = ./* ]]; then APPDIR=.; fi
@@ -20,11 +20,11 @@ if is_true "$UPDATE_BOOT_ORDER"; then
     primary_bn=${primary[0]}
     old_bn=${old[0]}
     if [ -z "$primary_bn" -o -z "$old_bn" ]; then
-        echo "Missing emboot EFI boot entries: not updating boot order" 1>&2
+        echo "Missing emboot EFI boot entries: not updating boot order"
         exit 1
     fi
     if [ "${efi_boot_order[0]}" == "$primary_bn" -a "${efi_boot_order[1]}" == "$old_bn" ]; then
-        echo "No need to update EFI boot order" 1>&2
+        echo "No need to update EFI boot order"
         exit 0
     fi
     new_boot_order=( $primary_bn $old_bn )
@@ -34,11 +34,11 @@ if is_true "$UPDATE_BOOT_ORDER"; then
         fi
     done
     IFS=','
-    echo "Updating EFI boot order to ${new_boot_order[*]}" 1>&2
+    echo "Updating EFI boot order to ${new_boot_order[*]}"
     efibootmgr -o "${new_boot_order[*]}"
     OFS=$oldIFS
 else
-    echo "Updating EFI boot order disabled by config" 1>&2
+    echo "Updating EFI boot order disabled by config"
 fi
 
 exit 0
diff --git a/prep_emboot_2 b/prep_emboot_2
--- a/prep_emboot_2
+++ b/prep_emboot_2
@@ -1,6 +1,6 @@
 #! /bin/bash
 
-exec 3>&1 1>&2
+exec 3>&1 >&2
 
 . /etc/efi-measured-boot/config
 . ./functions
@@ -30,27 +30,27 @@ update-initramfs -u -k all
 # Create a new key and add it to the LUKS header of the root partition
 mkdir -m 0700 -p $(dirname "$LUKS_KEY")
 if [ -e "$LUKS_KEY" ]; then
-    echo "Using existing key $LUKS_KEY" 1>&2
+    echo "Using existing key $LUKS_KEY" >&2
 else
-    echo "Generating new key for root partition LUKS header" 1>&2
+    echo "Generating new key for root partition LUKS header" >&2
     (umask 077 && dd if=/dev/urandom of="$LUKS_KEY" bs=128 count=1)
 fi
 if ! cryptsetup luksOpen --test-passphrase -d "$LUKS_KEY" "${cryptdev[1]}" </dev/null >/dev/null 2>&1; then
-    echo "You may be prompted to enter an existing LUKS passphrase for your root partition" 1>&2
+    echo "You may be prompted to enter an existing LUKS passphrase for your root partition" >&2
     cryptsetup luksAddKey "${cryptdev[1]}" "$LUKS_KEY"
 fi
 
-echo "Installing EFI blobs" 1>&2
+echo "Installing EFI blobs" >&2
 ./emboot_install
 
-echo "Adding EFI boot entries" 1>&2
+echo "Adding EFI boot entries" >&2
 ./emboot_update_efi_apps
 
-echo "Setting next EFI boot to latest emboot kernel blob" 1>&2
+echo "Setting next EFI boot to latest emboot kernel blob" >&2
 read_efi_vars
 bn=${efi_apps[$(emboot_loader_path | tr a-z A-Z)]%%$'\t'*}
 if [ -z "$bn" ]; then
-    echo "Can't find emboot EFI boot entry for $(emboot_loader_path)" 1>&2
+    echo "Can't find emboot EFI boot entry for $(emboot_loader_path)" >&2
     exit 1
 fi
 efibootmgr -n "$bn"
diff --git a/safety_checks b/safety_checks
--- a/safety_checks
+++ b/safety_checks
@@ -8,32 +8,32 @@ CHECKS=( root arch no_separate_boot mounted_efi root_luks systemd_stub tpm packa
 
 check_root() {
     if test "$(id -u)" != 0; then
-        echo "Must run as root (e.g., using sudo)" 1>&2
+        echo "Must run as root (e.g., using sudo)" >&2
         return 1
     fi
 }
 
 check_arch() {
     if test "$(uname -m)" != "x86_64"; then
-        echo "Unsupported architecture $(uname -m)" 1>&2
+        echo "Unsupported architecture $(uname -m)" >&2
         return 1
     fi
 }
 
 check_no_separate_boot() {
     if test "$(stat -c '%m' /boot)" != "/"; then
-        echo "/boot not on root device unsupported" 1>&2
+        echo "/boot not on root device unsupported" >&2
         return 1
     fi
 }
 
 check_mounted_efi() {
     if test "$(stat -c '%m' /boot/efi)" != "/boot/efi"; then
-        echo "EFI system partition must be mounted at /boot/efi" 1>&2
+        echo "EFI system partition must be mounted at /boot/efi" >&2
         return 1
     elif test "$(stat -f -c '%T' /boot/efi)" != "msdos" -o \
         "$(mount | awk '$3 == "/boot/efi" { print $5; }')" != "vfat"; then
-        echo "Filesystem mounted at /boot/efi must be mounted as type vfat" 1>&2
+        echo "Filesystem mounted at /boot/efi must be mounted as type vfat" >&2
         return 1
     fi
 }
@@ -41,11 +41,11 @@ check_mounted_efi() {
 check_root_luks() {
     cryptdev=( $(get_crypttab_entry $(get_device_info / | awk '{print $2;}') ) )
     if (( ${#cryptdev[@]} == 0 )); then
-        echo "Root has no parent crypttab entry" 1>&2
+        echo "Root has no parent crypttab entry" >&2
         return 1
     fi
     if [[ ${cryptdev[3]} != *luks* ]]; then
-        echo "crypttab entry missing luks option: ${cryptdev[3]}" 1>&2
+        echo "crypttab entry missing luks option: ${cryptdev[3]}" >&2
         return 1
     fi
     if ! cryptsetup isLuks "${cryptdev[1]}" --type luks2; then
@@ -56,21 +56,21 @@ check_root_luks() {
 
 check_systemd_stub() {
     if ! test -r "$SYSTEMD_STUB"; then
-        echo "systemd EFI stub $SYSTEMD_STUB not available" 1>&2
+        echo "systemd EFI stub $SYSTEMD_STUB not available" >&2
         return 1
     fi
 }
 
 check_tpm() {
     if ! tpm2_pcrread -Q 2>/dev/null; then
-        echo "TPM does not appear to be available or working" 1>&2
+        echo "TPM does not appear to be available or working" >&2
         return 1
     fi
 }
 
 check_packages() {
     if (( $(dpkg-query -W -f='${Status}\n' initramfs-tools 2>/dev/null | grep -c "ok installed") < 1 )); then
-        echo "initramfs-tools required (dracut is not supported)" 1>&2
+        echo "initramfs-tools required (dracut is not supported)" >&2
         return 1
     fi
 }
@@ -78,7 +78,7 @@ check_packages() {
 check_binaries() {
     for bin in sgdisk efibootmgr cryptsetup sed awk tr grep sort uniq diff basename dirname mount tpm2_create tpm2_createprimary tpm2_flushcontext tpm2_load tpm2_nvdefine tpm2_nvincrement tpm2_nvread tpm2_nvreadpublic tpm2_pcrread tpm2_policynv tpm2_policypcr tpm2_shutdown tpm2_startauthsession tpm2_unseal lsblk objcopy pip3 update-initramfs dd jq; do
         if [ -z "$(type -Pt "$bin")" ]; then
-            echo "Cannot find $bin in path" 1>&2
+            echo "Cannot find $bin in path" >&2
             return 1
         fi
     done
@@ -87,7 +87,7 @@ check_binaries() {
 check_cryptsetup_version() {
     cver=$(cryptsetup -V | awk '{print $2;}')
     if compare_versions "$cver" 2.4.0 || (( $? == 1 )); then
-        echo "cryptsetup version must be >= 2.4.0 (for --dump-json-metadata support)" 1>&2
+        echo "cryptsetup version must be >= 2.4.0 (for --dump-json-metadata support)" >&2
         return 1
     fi
 }
@@ -95,7 +95,7 @@ check_cryptsetup_version() {
 set -e
 
 for c in "${CHECKS[@]}"; do
-    echo -n "$c..." 1>&2
+    echo -n "$c..." >&2
     eval "check_$c"
-    echo "SUCCESS" 1>&2
+    echo "SUCCESS" >&2
 done
