Go back to using 2 kernel system with static EFI entries

diff --git a/prep_emboot b/prep_emboot
--- a/prep_emboot
+++ b/prep_emboot
@@ -77,7 +77,7 @@ revert_changes() {
     rm -f "$cfgfile.new"
 }
 
-trap revert_changes INT TERM ERR
+#trap revert_changes INT TERM ERR
 trap 'rc=$?; [ "$rc" -eq 0 ] && exit 0; revert_changes' EXIT
 
 # Write config
@@ -101,8 +101,13 @@ EOF
 
 # Modify crypttab
 echo "Modifying crypttab"
-cat /etc/crypttab | awk -v newopts="$cryptopts" '$1 == "'"${cryptdev[0]}"'" && $2 == "'"${cryptdev[1]}"'" { print "#" $0; print $1 " " $2 " " $3 " " newopts; next; }  { print $0; }' >/etc/crypttab.new
-mv -f /etc/crypttab /etc/crypttab.pre_emboot
-mv -f /etc/crypttab.new /etc/crypttab
+cat /etc/crypttab | awk -v newopts="$cryptopts" '$1 == "'"${cryptdev[0]}"'" && $2 == "'"${cryptdev[1]}"'" { print $1 " " $2 " " $3 " " newopts; next; } { print $0; }' >/etc/crypttab.new
+if diff -q /etc/crypttab /etc/crypttab.new >/dev/null 2>&1; then
+    echo "No crypttab change required"
+    rm -f /etc/crypttab.new
+else
+    mv -f /etc/crypttab /etc/crypttab.pre_emboot
+    mv -f /etc/crypttab.new /etc/crypttab
+fi
 
 exit 0
diff --git a/prep_emboot_2 b/prep_emboot_2
--- a/prep_emboot_2
+++ b/prep_emboot_2
@@ -46,16 +46,10 @@ echo "Adding EFI boot entries" 1>&2
 ./emboot_update_efi_apps
 
 echo "Setting next EFI boot to latest emboot kernel blob" 1>&2
-kvers=( $(list_emboot_kernel_versions) )
-if (( ${#kvers[@]} == 0 )); then
-    echo "Can't find any emboot kernel blobs" 1>&2
-    exit 1
-fi
-pk=${kvers[0]}
-read_emboot_efi_apps
-bn=${emboot_efi_apps[$(echo -n "$pk" | tr a-z A-Z)]}
+read_efi_apps
+bn=${efi_apps[$(emboot_loader_path)]}
 if [ -z "$bn" ]; then
-    echo "Can't find emboot EFI boot entry for kernel $pk" 1>&2
+    echo "Can't find emboot EFI boot entry for $(emboot_loader_path)" 1>&2
     exit 1
 fi
 efibootmgr -n "$bn"
