WIP

diff --git a/prep_emboot_2 b/prep_emboot_2
--- a/prep_emboot_2
+++ b/prep_emboot_2
@@ -22,7 +22,7 @@ revert_changes() {
     fi
 }
 
-trap revert_changes INT TERM ERR
+#trap revert_changes INT TERM ERR
 trap 'rc=$?; [ "$rc" -eq 0 ] && exit 0; revert_changes' EXIT
 
 # Update initrd according to newly-installed hook
@@ -46,11 +46,18 @@ echo "Adding EFI boot entries" 1>&2
 ./emboot_update_efi_apps
 
 echo "Setting next EFI boot to latest emboot kernel blob" 1>&2
-./read_emboot_efi_apps
-if (( ${#emboot_efi_apps[@]} == 0 )); then
-    echo "Can't find any emboot EFI boot entries" 1>&2
+kvers=( $(list_emboot_kernel_versions) )
+if (( ${#kvers[@]} == 0 )); then
+    echo "Can't find any emboot kernel blobs" 1>&2
     exit 1
 fi
-efibootmgr -n "${emboot_efi_apps[0]}"
+pk=${kvers[0]}
+read_emboot_efi_apps
+bn=${emboot_efi_apps[$(echo -n "$pk" | tr a-z A-Z)]}
+if [ -z "$bn" ]; then
+    echo "Can't find emboot EFI boot entry for kernel $pk" 1>&2
+    exit 1
+fi
+efibootmgr -n "$bn"
 
 exit 0
