Switch from tpm_futurepcr to pcr-oracle for predicting measurements

diff --git a/safety_checks b/safety_checks
--- a/safety_checks
+++ b/safety_checks
@@ -1,7 +1,7 @@
 #! /bin/bash
 
 SYSTEMD_STUB=/usr/lib/systemd/boot/efi/linuxx64.efi.stub
-CHECKS=( root arch no_separate_boot mounted_efi root_luks systemd_stub tpm tpm_futurepcr packages binaries cryptsetup_version )
+CHECKS=( root arch no_separate_boot mounted_efi root_luks systemd_stub tpm pcr_oracle packages binaries cryptsetup_version )
 
 APPDIR=.
 . ./bash_functions
@@ -77,10 +77,16 @@ check_packages() {
         echo "initramfs-tools required (dracut is not supported)" >&2
         return 1
     fi
+    for pkg in json-c tss2-esys; do
+        if ! pkg-config --exists $pkg; then
+            echo "Dev package for $pkg is required to build pcr-oracle" >&2
+            return 1
+        fi
+    done
 }
 
 check_binaries() {
-    for bin in sgdisk efibootmgr cryptsetup sed awk tr grep sort uniq diff basename dirname mount tpm2_create tpm2_createprimary tpm2_flushcontext tpm2_load tpm2_nvdefine tpm2_nvincrement tpm2_nvread tpm2_nvreadpublic tpm2_pcrread tpm2_policynv tpm2_policypcr tpm2_shutdown tpm2_startauthsession tpm2_unseal lsblk objcopy pipx update-initramfs dd jq; do
+    for bin in sgdisk efibootmgr cryptsetup sed awk tr grep sort uniq diff basename dirname mount tpm2_create tpm2_createprimary tpm2_flushcontext tpm2_load tpm2_nvdefine tpm2_nvincrement tpm2_nvread tpm2_nvreadpublic tpm2_pcrread tpm2_policynv tpm2_policypcr tpm2_shutdown tpm2_startauthsession tpm2_unseal lsblk objcopy update-initramfs dd jq; do
         if [ -z "$(type -Pt "$bin")" ]; then
             echo "Cannot find $bin in path" >&2
             return 1
@@ -96,9 +102,9 @@ check_cryptsetup_version() {
     fi
 }
 
-check_tpm_futurepcr() {
-    if [ ! -r tpm_futurepcr/setup.py ]; then
-        echo "tpm_futurepcr/setup.py does not exist; did you forget to clone --recurse?" >&2
+check_pcr_oracle() {
+    if [ ! -r pcr-oracle/configure ]; then
+        echo "pcr-oracle/configure does not exist; did you forget to clone --recurse?" >&2
         return 1
     fi
 }
