require cryptsetup-initramfs

diff --git a/safety_checks b/safety_checks
--- a/safety_checks
+++ b/safety_checks
@@ -69,6 +69,10 @@ check_tpm() {
 }
 
 check_packages() {
+    if (( $(dpkg-query -W -f='${Status}\n' cryptsetup-initramfs 2>/dev/null | grep -c "ok installed") < 1 )); then
+        echo "cryptsetup-initramfs required" >&2
+        return 1
+    fi
     if (( $(dpkg-query -W -f='${Status}\n' initramfs-tools 2>/dev/null | grep -c "ok installed") < 1 )); then
         echo "initramfs-tools required (dracut is not supported)" >&2
         return 1
